name: Android Pipeline

on:
  push:
  pull_request:
  
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      shell: bash
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace
        
  Unit_Test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [Build]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Run Unit Tests
      shell: bash
      run: |
        chmod +x ./gradlew
        ./gradlew testDebug --info
        
  UI_Test:
    name: UI Tests
    continue-on-error: true
    runs-on: macos-latest
    needs: [Build]
    
    strategy:
      matrix:
        api-level: [29, 30]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: playstore
        script: |
          chmod +x ./gradlew
          ./gradlew connectedCheck --info
